name: Frontend Test

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  codecov-token:
    description: 'Codecov Token'
    required: true
runs:

  using: composite
  steps:
    - id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Npm install
      shell: bash
      working-directory: ui
      run: npm ci

    - name: Npm lint
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ inputs.github-token }}
        reporter: github-pr-review # Change reporter.
        workdir: "ui"

    - name: Npm - Run build
      shell: bash
      working-directory: ui
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
      run: npm run build

    - name: Run front-end unit tests
      shell: bash
      working-directory: ui
      run: npm run test:unit

    - name: Install Playwright
      shell: bash
      working-directory: ui
      run: npx playwright install --with-deps

    - name: Build Storybook
      shell: bash
      working-directory: ui
      run: npm run build-storybook --quiet

    - name: Storybook - Run tests
      shell: bash
      working-directory: ui
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test:storybook"