name: kestra-devtools test

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'dev-tools/kestra-devtools/**'

env:
  # to save corepack from itself
  COREPACK_INTEGRITY_KEYS: 0

jobs:
  test:
    name: kestra-devtools tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Npm - install
        working-directory: 'dev-tools/kestra-devtools'
        run: npm ci

      - name: Run tests
        working-directory: 'dev-tools/kestra-devtools'
        run: npm run test

      - name: Npm - Run build
        working-directory: 'dev-tools/kestra-devtools'
        run: npm run build
