name: Main Workflow

on:
  push:
    branches:
      - releases/*
      - develop

  workflow_dispatch:
    inputs:
      skip-test:
        description: 'Skip test'
        type: choice
        required: true
        default: 'false'
        options:
          - "true"
          - "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  backend-tests:
    name: Backend tests
    if: ${{ github.event.inputs.skip-test == 'false' || github.event.inputs.skip-test == '' }}
    uses: kestra-io/actions/.github/workflows/kestra-oss-backend-tests.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  frontend-tests:
    name: Frontend tests
    if: ${{ github.event.inputs.skip-test == 'false' || github.event.inputs.skip-test == '' }}
    uses: kestra-io/actions/.github/workflows/kestra-oss-frontend-tests.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish-develop-docker:
    name: Publish Docker
    needs: [backend-tests, frontend-tests]
    if: "!failure() && !cancelled() && github.ref == 'refs/heads/develop'"
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-docker.yml@main
    with:
      plugin-version: 'LATEST-SNAPSHOT'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


  publish-develop-maven:
    name: Publish develop Maven
    needs: [ backend-tests, frontend-tests ]
    if: "!failure() && !cancelled() && github.ref == 'refs/heads/develop'"
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-maven.yml@main
    secrets:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
      SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
      SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}

  end:
    runs-on: ubuntu-latest
    needs: [publish-develop-docker, publish-develop-maven]
    if: always()
    steps:
      - name: Trigger EE Workflow
        uses: peter-evans/repository-dispatch@v3
        if: github.ref == 'refs/heads/develop' && needs.release.result == 'success'
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          repository: kestra-io/kestra-ee
          event-type: "oss-updated"

      # Slack
      - name: Slack - Notification
        if: ${{ failure() && env.SLACK_WEBHOOK_URL != 0 && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        uses: kestra-io/actions/composite/slack-status@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
