name: Pre Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-artifacts:
    name: Build Artifacts
    uses: kestra-io/actions/.github/workflows/kestra-oss-build-artifacts.yml@main

  backend-tests:
    name: Backend tests
    uses: kestra-io/actions/.github/workflows/kestra-oss-backend-tests.yml@main
    secrets:
      GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

  frontend-tests:
    name: Frontend tests
    uses: kestra-io/actions/.github/workflows/kestra-oss-frontend-tests.yml@main
    secrets:
      GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish-maven:
    name: Publish Maven
    needs: [ backend-tests, frontend-tests ]
    if: "!failure() && !cancelled()"
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-maven.yml@main
    secrets:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
      SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
      SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}

  publish-github:
    name: Github Release
    needs: [build-artifacts, backend-tests, frontend-tests]
    if: "!failure() && !cancelled()"
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-github.yml@main
    secrets:
      GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
      SLACK_RELEASES_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_WEBHOOK_URL }}
