name: Publish docker

on:
  workflow_dispatch:
    inputs:
      retag-latest:
        description: 'Retag latest Docker images'
        required: true
        type: boolean
        default: false
      retag-lts:
        description: 'Retag LTS Docker images'
        required: true
        type: boolean
        default: false
      plugin-version:
        description: 'Plugin version'
        required: false
        type: string
        default: "LATEST"

jobs:
  publish-docker:
    name: Publish Docker
    if: startsWith(github.ref, 'refs/tags/v')
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-docker.yml@main
    with:
      plugin-version: ${{ inputs.plugin-version }}
      retag-latest: ${{ inputs.retag-latest }}
      retag-lts: ${{ inputs.retag-lts }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
