name: Update and Tag Kestra Plugins

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The release version (e.g., 0.21.0)'
        required: true
        type: string
      dryRun:
        description: 'Use DRY_RUN mode'
        required: false
        default: 'false'
jobs:
  tag:
    name: Release plugins
    runs-on: kestra-private-standard
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get Plugins List
      - name: Get Plugins List
        uses: ./.github/actions/plugins-list
        if: "!startsWith(github.ref, 'refs/tags/v')"
        id: plugins-list
        with:
          plugin-version: 'LATEST'

      # Execute
      - name: Tag Plugins
        if: ${{ github.event.inputs.dryRun == 'false' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./tag-release-plugins.sh;
          ./tag-release-plugins.sh \
          --release-version=${{github.event.inputs.releaseVersion}} \
          --yes \
           ${{ steps.plugins-list.outputs.repositories }}

      - name: Run Gradle Release (DRY_RUN)
        if: ${{ github.event.inputs.dryRun == 'true' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./tag-release-plugins.sh;
          ./tag-release-plugins.sh \
          --release-version=${{github.event.inputs.releaseVersion}} \
          --dry-run \
          --yes \
          ${{ steps.plugins-list.outputs.repositories }}