name: Github - Release

on:
  workflow_call:
    secrets:
      GH_PERSONAL_TOKEN:
        description: "The Github personal token."
        required: true
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Github - Release
    runs-on: ubuntu-latest
    steps:
      # Download Exec
      - name: Artifacts - Download executable
        uses: actions/download-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: exe
          path: build/executable

      # Check out
      - name: Checkout - Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Checkout GitHub Actions
      - name: Checkout - Actions
        uses: actions/checkout@v4
        with:
          repository: kestra-io/actions
          sparse-checkout-cone-mode: true
          path: actions
          sparse-checkout: |
            .github/actions

      # GitHub Release
      - name: Create GitHub release
        uses: ./actions/.github/actions/github-release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          SLACK_RELEASES_WEBHOOK_URL: ${{ secrets.SLACK_RELEASES_WEBHOOK_URL }}

