name: Publish - Maven

on:
  workflow_call:
    secrets:
      SONATYPE_USER:
        description: "The Sonatype username."
        required: true
      SONATYPE_PASSWORD:
        description: "The Sonatype password."
        required: true
      SONATYPE_GPG_KEYID:
        description: "The Sonatype GPG key id."
        required: true
      SONATYPE_GPG_PASSWORD:
        description: "The Sonatype GPG password."
        required: true
      SONATYPE_GPG_FILE_ASCII:
        description: "The Sonatype GPG file in ASCII format."
        required: true

jobs:
  publish:
    name: Publish - Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Current ref
        uses: actions/checkout@v4

      # Setup build
      - name: Setup - Build
        uses: kestra-io/actions/.github/actions/setup-build@main
        id: build
        with:
          java-enabled: true
          node-enabled: true

      # Publish
      - name: Publish - Release package to Maven Central
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SONATYPE_GPG_KEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SONATYPE_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SONATYPE_GPG_FILE_ASCII}}
        run: ./gradlew publishToMavenCentral

      # Gradle dependency
      - name: Java - Gradle dependency graph
        uses: gradle/actions/dependency-submission@v4